---
- name: Déployer les conteneurs
  import_playbook: 01_deploy_node.yml

- hosts: mantis
  roles:
          - ansible-role-mantis

- hosts: databases
  roles:
          - ansible-role-postgresql

- hosts: reverse_proxy
  roles:
          - ansible-role-reverse-proxy
